### ISSUE TITLE
Producing with Snappy compression fails

### ISSUE THREAD

**Issue by nscuro** [tansu-io/tansu#67]
Hi, thanks for this cool project!

I'm trying to give this a spin with our project, but running into issues where Tansu fails to process Snappy-compressed records. I'm using PostgreSQL as storage backend.

Repro steps are quite straightforward:

1. Launch Kafka container and attach to Tansu's Compose network
    ```shell
    docker run -it --rm --network tansu_default -w /opt/kafka/bin apache/kafka:3.8.0 /bin/bash
    ```
2. Create a topic:
    ```shell
    ./kafka-topics.sh --bootstrap-server tansu:9092 --create --topic foo --partitions 3
    ```
3. Produce a record with Snappy compression:
    ```shell
    ./kafka-console-producer.sh --bootstrap-server tansu:9092 --compression-codec snappy --topic foo
    >bar
    [2024-10-07 20:26:30,977] ERROR Error when sending message to topic foo with key: null, value: 3 bytes with error: (org.apache.kafka.clients.producer.internals.ErrorLoggingCallback)
    org.apache.kafka.common.errors.UnknownServerException: The server experienced an unexpected error when processing the request.
    ```

When this happens, tansu-server logs the following error:
```
ERROR ThreadId(04) tansu_server::broker::produce: 66: err=KafkaSansIo(Io(Custom { kind: Other, error: StreamHeader { byte: 130 } }))
```

Tested image is `ghcr.io/tansu-io/tansu@sha256:33aa04fc31c6a583469df3b4c14623a075f483eb8ca48ab256142ef10d828b94`

**Comment by shortishly** [comment]
Thanks the report and comments :)


The Java client frames the snappy compressed data, with: [magic header:16 bytes]([block size:int32][compressed data:byte array])* (https://github.com/xerial/snappy-java/tree/master?tab=readme-ov-file#compatibility-notes). Whereas, librdkafka doesn't frame the compressed data at all. I've changed the inflator to skip the Java magic header (20 bytes), and assumed unframed data for all other clients.

Checked with:

```
echo "Lorem ipsum..." | kafka-console-producer --topic compression --bootstrap-server localhost:9092 --compression-codec snappy
```

and:

```
echo "Lorem ipsum..." | ./examples/rdkafka_example -P -t benchmark -b localhost:9092 -z snappy

```

Tests updated to decode produce requests with both Java style framed and unframed compressed data.
