### ISSUE TITLE
amazon s3 / minio parity for conditional PUT requests, compare and set operation 

### ISSUE THREAD

**Issue by gedw99** [tansu-io/tansu#70]
https://aws.amazon.com/about-aws/whats-new/2024/08/amazon-s3-conditional-writes/

Looks like there is full parity 3 week ago. see : https://github.com/minio/minio/discussions/20318

Compare and set operation, is possible redundant...

**Comment by shortishly** [comment]
Tansu requires that the underlying S3 service support conditional requests. While [AWS S3 does now support conditional
writes][aws-s3-conditional-writes], the support is [limited to not overwriting an existing object][aws-s3-conditional-requests].  To have stateless brokers we need to [use a compare and set operation][tigris-conditional-writes], which is not currently available in AWS S3.

Tansu uses [object store][crates-io-object-store], which provides a multi-cloud API for storage. There is an alternative option to use a [DynamoDB-based commit protocol, to provide conditional write support for AWS S3][object-store-dynamo-conditional-put] instead.

[object-store-dynamo-conditional-put]: https://docs.rs/object_store/0.11.0/object_store/aws/struct.DynamoCommit.html
[crates-io-object-store]: https://crates.io/crates/object_store
[object-store-conditional-put]: https://docs.rs/object_store/0.11.0/object_store/aws/enum.S3ConditionalPut.html
[aws-s3-conditional-requests]: https://docs.aws.amazon.com/AmazonS3/latest/userguide/conditional-requests.html
[aws-s3-conditional-writes]: https://aws.amazon.com/about-aws/whats-new/2024/08/amazon-s3-conditional-writes/
[tigris-conditional-writes]: https://www.tigrisdata.com/blog/s3-conditional-writes/

**Comment by shortishly** [comment]
Yes, they're completely independent . You can use S3 (minio) without PostgreSQL.

It looks like the golang client uses librdkafka, so it should work fine. 
Raise an issue, if you encounter a problem.

The main outstanding areas that aren't supported in Tansu: Transactions and Idempotent producer.
